apiVersion: v1
kind: Service
metadata:
  name: capstone-loadbalancer
  annotations:
    external-dns.alpha.kubernetes.io/hostname: misan.vidly.com
spec:
  type: LoadBalancer
  selector:
    app: capstone
  ports:
    - port: 80
      targetPort: 8080